### ISSUE TITLE
Discoverability from Gradle

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle-completion#17]
It would be great to make the completion plugin discoverable from Gradle. For example when you first run Gradle from bash or zsh, it could ask you whether you want to install completion as well. Then when you press "Y" it would download and install it.

**Comment by eriwen** [comment]
This is just a way to trigger installation from gradle/gradle, correct?

**Comment by eriwen** [comment]
Also, this seems like something that should be filed on that project unless there are changes to this one needed to make that happen.

**Comment by pioterj** [comment]
Yes, from Gradle Build Tool. Good point, it should probably be an issue on https://github.com/gradle/gradle.

**Comment by eriwen** [comment]
Closing as superseded by https://github.com/gradle/gradle/issues/1550
