### ISSUE TITLE
Feature request: Create Homebrew Formula

### ISSUE THREAD

**Issue by matsev** [gradle/gradle-completion#21]
Create [Homebrew](https://brew.sh/) formula to simplify installation.
For the record, there is a [Formula for Gradle](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gradle.rb).

**Comment by eriwen** [comment]
Very good idea!

**Comment by iamtodor** [comment]
Doesn't work for `gradle installDebug`. The completion for `gradle i [TAB]' is only `gradle init`.

**Comment by eriwen** [comment]
@iamtodor Did you mean to file a separate issue?

**Comment by iamtodor** [comment]
@eriwen could you describe your question in other words? Don't get the question

**Comment by eriwen** [comment]
@iamtodor I apologize for the brief response from my phone earlier. It seems like you're comment isn't about homebrew, so I suggest a new issue.

Does it work if you run `export GRADLE_COMPLETION_UNQUALIFIED_TASKS="true"` and regenerate the completion cache (by changing your build.gradle, say)?

**Comment by johnzeringue** [comment]
This has already been done. See https://github.com/Homebrew/homebrew-core/blob/master/Formula/gradle-completion.rb

**Comment by eriwen** [comment]
Heck yeah! Thanks @johnzeringue! 

One thing though: when I try to `brew install gradle-completion` I get:

> Could not symlink share/zsh/site-functions/_gradle
/usr/local/share/zsh/site-functions is not writable.
> You can try again using:
  brew link gradle-completion

Which doesn't quite work. Is there a way we can fix that?

**Comment by johnzeringue** [comment]
Sounds like a permissions issue. I would check that the directory isn’t owned by root

**Comment by eriwen** [comment]
@johnzeringue You are correct. The thing that confuses me is that other tools have installed completion through brew given the same permissions on `/usr/local/share/zsh` (which was owned by root btw). Just curious if `brew` has some way to link to that directory as root.

**Comment by paour** [comment]
Note that since the latest release of `gradle-completion` is quite old, you need to install as `brew install gradle-completion --HEAD` to get the latest features.

**Comment by johnzeringue** [comment]
@eriwen `brew` is optimized around doing things without root and encourages you to `chown` in situations like this

**Comment by eriwen** [comment]
Ok, in that case I'll consider this closed as delivered, and will cut a new version of gradle-completion for brew.
