### ISSUE TITLE
Completion on subprojects doesn't work as expected

### ISSUE THREAD

**Issue by HeadOnAPlate** [gradle/gradle-completion#24]
Instead of completing on **:\<subproject>:\<task>** it completes on **\<subproject>:\<task>**.
Notice the missing **:** at the start.

Gradle seems to support both syntaxes (not sure when the one without leading colon was introduced), so it should complete in both situations.

**Comment by eriwen** [comment]
@HeadOnAPlate To clarify: are you saying that `:foo:b[TAB]` does not work, but `foo:b[TAB]` does?

Could you please provide environment information like OS and whether you're using bash or zsh?

**Comment by HeadOnAPlate** [comment]
E.g. I have a gradle project that includes `foo` as a subproject in the settings.gradle file.
The foo subproject specifies a task `bar`.
`f[tab]` would be completed to `foo:`, whereas `:f[tab]` is not completed at all.
`foo:b[tab]` completes without a hitch.

When just typing it out, gradle accepts both syntaxes: `:foo:bar` and `foo:bar`, so I believe completion should work for both as well.

I'm on OS X Sierra, terminal (so that's bash 3.2.57)

**Comment by eriwen** [comment]
Thanks for the response. Please see my comment on #25 and let me know what you see in the completion cache. `:f[TAB]` should definitely work. If it doesn't, that's a bug.

**Comment by HeadOnAPlate** [comment]
```
✔  22:19 ~/git/platform-infrastructure [ 51/develop | ● 11 ✚ 44 ⚑ 2 ] $ cat ~/.gradle/completion/bc9b5c5b6b04cae84f19b4f7a3a39c3d | grep assemble
assemble  - Assembles the outputs of this project.
agent-core:assemble  - Assembles the outputs of this project.
agent-rest-client:assemble  - Assembles the outputs of this project.
agent-web:assemble  - Assembles the outputs of this project.
console-configuration:assemble  - Assembles the outputs of this project.
console-core:assemble  - Assembles the outputs of this project.
console-graphql:assemble  - Assembles the outputs of this project.
console-rest-client:assemble  - Assembles the outputs of this project.
console-ui:assemble  - Assembles the outputs of this project.
console-web:assemble  - Assembles the outputs of this project.
migration:assemble  - Assembles the outputs of this project.
:migration:assemble  - Assembles the outputs of this project.
platform-common:assemble  - Assembles the outputs of this project.
upgrade:assemble  - Assembles the outputs of this project.
:upgrade:assemble  - Assembles the outputs of this project.
```

I'm getting a strange mix in the cache.
It appears that for the `upgrade` and `migration` subprojects autocompletion "just works", whereas the other subprojects only complete with the non-prefixed version.

I tried clearing the cache to make sure it wasn't a one-time occurrence, but the freshly generated cache was identical (even the filename, which is a checksum I believe?).

**Comment by eriwen** [comment]
Well now that's much more interesting. 

I see it. I bet it's because of the "-" in the project name. Wanna fix that bug with some regex?

**Comment by eriwen** [comment]
If you want to fix it. It's this line: https://github.com/gradle/gradle-completion/blob/master/gradle-completion.bash#L178

Otherwise I'll take a look at it this weekend.

Bonus points if you do this for zsh as well.

**Comment by HeadOnAPlate** [comment]
I updated the PR. Seems to work great now. Same fix applied to the zsh completion file.

```
✔  23:14 ~/git/platform-infrastructure [ 51/develop | ● 11 ✚ 44 ⚑ 2 ] $ cat ~/.gradle/completion/bc9b5c5b6b04cae84f19b4f7a3a39c3d | grep assemble
assemble  - Assembles the outputs of this project.
agent-core:assemble  - Assembles the outputs of this project.
:agent-core:assemble  - Assembles the outputs of this project.
agent-rest-client:assemble  - Assembles the outputs of this project.
:agent-rest-client:assemble  - Assembles the outputs of this project.
agent-web:assemble  - Assembles the outputs of this project.
:agent-web:assemble  - Assembles the outputs of this project.
console-configuration:assemble  - Assembles the outputs of this project.
:console-configuration:assemble  - Assembles the outputs of this project.
console-core:assemble  - Assembles the outputs of this project.
:console-core:assemble  - Assembles the outputs of this project.
console-graphql:assemble  - Assembles the outputs of this project.
:console-graphql:assemble  - Assembles the outputs of this project.
console-rest-client:assemble  - Assembles the outputs of this project.
:console-rest-client:assemble  - Assembles the outputs of this project.
console-ui:assemble  - Assembles the outputs of this project.
:console-ui:assemble  - Assembles the outputs of this project.
console-web:assemble  - Assembles the outputs of this project.
:console-web:assemble  - Assembles the outputs of this project.
migration:assemble  - Assembles the outputs of this project.
:migration:assemble  - Assembles the outputs of this project.
platform-common:assemble  - Assembles the outputs of this project.
:platform-common:assemble  - Assembles the outputs of this project.
upgrade:assemble  - Assembles the outputs of this project.
:upgrade:assemble  - Assembles the outputs of this project.
```
