### ISSUE TITLE
Breaks file completion in bash

### ISSUE THREAD

**Issue by tomdcc** [gradle/gradle-completion#35]
If trying to reference a file when completing a gradle command, tab-completion no longer works.

E.g. `./gradlew -I ../[tab]` to find an init script does not work.

Tested with Gradle 4.0, Bash 3.2.57(1)-release, MacOS 10.12.5

**Comment by eriwen** [comment]
Fixed by eeefb043abc5398efb726303ac128b655d16d3ac
