### ISSUE TITLE
Cannot complete second task

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle-completion#41]
I am using the current master ( cd0b98ed6a685fd8fd96d6f215750dddfd363dba ) of `gradle-completion` on the Gradle build itself.
I seem to only be able to complete the first task. After that, I can only complete command line options. I think I also had the problem the other way round - I was only able to complete tasks but no command line options anymore.

https://asciinema.org/a/46jjfXTdkGyH7yq4IdFNv79vo

**Comment by pkubowicz** [comment]
Also the option completion stops working if you type two tasks:
```
gradle build test --<tab>
```
You don't get any suggestions.

Tested on Zsh 5.2.

**Comment by eriwen** [comment]
@wolfs This is fixed with 31ae17341da90c22a3635601afcfb9ef082de622

@pkubowicz I've filed #47 to address this separately
