### ISSUE TITLE
--include-build is suggested only once in Zsh

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle-completion#45]
If you type `gradle build --include-build ../foo --in` you are suggested `--info` and `--init-script` but not `--include-build`, although it is legal to pass this option many times.

**Comment by eriwen** [comment]
Fixed with eed7654819122ee1f722b0074924bf44063d1af7

**Comment by pkubowicz** [comment]
@eriwen This does not work for me. I type `gradle --include-build ../foo --incl` and I get
```
Completing no arguments
Completing ->argument-expected
```

**Comment by eriwen** [comment]
@pkubowicz I'm so sorry. https://github.com/gradle/gradle-completion/commit/eed7654819122ee1f722b0074924bf44063d1af7 covers `--init-script` and not `--include-build`. 

I believe this should be working for you now with 960390dadb5dc77e45d0898a0c61aaff57a9009e. I am concerned that you're getting different behavior than when I'm testing, though. Please try this out and if it doesn't work, 2 things would be super-helpful:
 1) Environment information
 2) [Capture a debug trace](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#testing--debugging) with `Ctrl+X ?`

Thanks for your continued feedback.

**Comment by pkubowicz** [comment]
There is a discrepancy now: `gradle build --include-build <tab>` prints `Completing all tasks` but `gradle --include-build <tab>` correctly suggests directories.

I have [a stack trace](https://drive.google.com/open?id=1lgmr5lxNJNqMjndHLZeE4bk50DZXJhVN) for the case where pressing Tab multiple ties does not help.
