### ISSUE TITLE
Last update broke completion in bash

### ISSUE THREAD

**Issue by NielsDoucet** [gradle/gradle-completion#54]
It seems with the latest update, all of the module and task completions are broken in bash.
`:mo` gets completed to `::module`
`:module:ta` gets completed to `:module::module:task`
These prevent further completion because of the presence of `::` in all of these cases.

`mo` get completed correctly to `module:`, but then `module:ta` is broken again, resulting in `module:module:task`

**Comment by tanadeau** [comment]
I just saw the same issue after updating from Homebrew.

**Comment by eriwen** [comment]
I apologize for the delay addressing this serious issue. I let this lapse during the holidays. 

v1.3.1 is out now and fixes this issue.

**Comment by tanadeau** [comment]
I saw the update about the fix earlier this morning. I updated, and everything is working fine again. Thanks again! 😄

**Comment by NielsDoucet** [comment]
No problem. I managed with a previous version until now.
Thanks for the update :smile: 

I hope you enjoyed your holidays!

**Comment by eriwen** [comment]
Thanks folks :). Holidays were relaxing. I hope yours were too.
