### ISSUE TITLE
completion does not work for gradle scripts using kotlin

### ISSUE THREAD

**Issue by abendt** [gradle/gradle-completion#57]
given
* gradle flie build.gradle.kts and 
* an empty settings.gradle.kts

with this configuration the completion does not detect the build file and does not show the tasks.

it works when i rename settings.gradle.kts to settings.gradle and 
add an entry rootProject.buildFileName = "build.gradle.kts"

it would be nice if the completion logic also would detect the buildfile without that

**Comment by NielsDoucet** [comment]
This commit seems to have broken completion in bash.
I'll see if I can pin down where it goes wrong.
